server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/yhjr_postloan?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      
  #多数据源配置
  second-datasource:
    jdbc-url: jdbc:mysql://127.0.0.1:3306/yhjr_postloan?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  #redis配置
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
  #rabbitMq 
  rabbitmq:
    addresses: 10.253.129.8
    port: 5672
    username: yhjr
    password: yhjr
    publisher-confirms: true    #  消息发送到交换机确认机制,是否确认回调
    publisher-returns: true   #发送是否确认
    listener:
      simple:
        acknowledge-mode: manual #消费手动确认ack
pagehelper:
  helper-dialect: mysql
  offsetAsPageNum: true
  rowBoundsWithCount: true
  reasonable: false
  pageSizeZero: true
  support-methods-arguments: true
  params: count=countSql

  
mybatis:
  type-aliases-package: cn.beyond.beyond.entity
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
    
    
jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop



#注入对象
person:
  name: jack
  des: sex
  like:
    - 篮球
    - 冰球
  student:
    name: jenny
    xb: nn

